### ISSUE TITLE
Failed to load dynamic library 'sqlite3.dll'

### ISSUE THREAD

**Issue by tbsmanish** [thitlwincoder/browser_data#1]
Note: I do have .dll file in lib folder near main.dart file. I am using flutter 3.19.0.

### CODE:

` var browser = Chrome(sqlite3Path: './sqlite3.dll');
var histories = await browser.fetchHistory(limit: 2);`

### ERROR:

`[+2097 ms] [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'sqlite3.dll': The specified module could not be found.
[        ]  (error code: 126)
[        ] #0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:43)
[        ] #1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22:12)
[        ] #2      new Browser.<anonymous closure> (package:browser_data/generic.dart:40:48)
[        ] #3      OpenDynamicLibrary.openSqlite (package:sqlite3/src/ffi/load_library.dart:119:20)
[        ] #4      sqlite3 (package:sqlite3/src/ffi/api.dart:13:39)
[        ] #5      Browser.fetchHistory (package:browser_data/generic.dart:137:11)
[        ] <asynchronous suspension>
[        ] #6      _MyAppState.initPlatformState (package:testproject/main.dart:46:23)
[        ] <asynchronous suspension>`

**Comment by thitlwincoder** [comment]
If you use this package in flutter, you can use with `rootBundle`.

**Comment by tbsmanish** [comment]
can you please provide an example or how to do it with rootBundle..

**Comment by thitlwincoder** [comment]
Have you try without `sqlite3Path` parameter?

```dart
var browser = Chrome();
var histories = await browser.fetchHistory(limit: 2);
```
